/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuutama;

import java.awt.CardLayout;

/**
 *
 * @author ENMA
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        
        // Set initial
        setVisible(true);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        // Inisialisasi ContentPanel dulu
        ContentPanel = new javax.swing.JPanel();
        ContentPanel.setLayout(new java.awt.CardLayout());
        // Tambahkan card ke ContentPanel
        ContentPanel.add(new alternatif(),"alternatif");
        ContentPanel.add(new PengaturanKriteria(),"kriteria");
        ContentPanel.add(new Seleksi(),"seleksi");
         content.add(ContentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        alternatif = new javax.swing.JButton();
        kriteria = new javax.swing.JButton();
        seleksi = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        laporanDataPaket = new javax.swing.JLabel();
        laporanPrioritasKriteria = new javax.swing.JLabel();
        laporanHasilSeleksi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 174, 228));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        alternatif.setBackground(new java.awt.Color(91, 174, 228));
        alternatif.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        alternatif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paket.png"))); // NOI18N
        alternatif.setText("ALTERNATIF");
        alternatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alternatifMouseClicked(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(91, 174, 228));
        kriteria.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        kriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folderrrr.png"))); // NOI18N
        kriteria.setText("KRITERIA");
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }
        });

        seleksi.setBackground(new java.awt.Color(91, 174, 228));
        seleksi.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        seleksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hitung.png"))); // NOI18N
        seleksi.setText("SELEKSI");
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(91, 174, 228));
        laporan.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporannnn.png"))); // NOI18N
        laporan.setText("LAPORAN");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(91, 174, 228));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setText("LOG OUT");

        laporanDataPaket.setBackground(new java.awt.Color(255, 237, 192));
        laporanDataPaket.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        laporanDataPaket.setForeground(new java.awt.Color(86, 169, 222));
        laporanDataPaket.setText("    Laporan Paket Makanan");
        laporanDataPaket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanDataPaket.setOpaque(true);
        laporanDataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanDataPaketMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanDataPaketMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanDataPaketMouseEntered(evt);
            }
        });

        laporanPrioritasKriteria.setBackground(new java.awt.Color(255, 237, 192));
        laporanPrioritasKriteria.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        laporanPrioritasKriteria.setForeground(new java.awt.Color(86, 169, 222));
        laporanPrioritasKriteria.setText("   Laporan Prioritas Kriteria");
        laporanPrioritasKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasKriteria.setOpaque(true);
        laporanPrioritasKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseEntered(evt);
            }
        });

        laporanHasilSeleksi.setBackground(new java.awt.Color(255, 237, 192));
        laporanHasilSeleksi.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        laporanHasilSeleksi.setForeground(new java.awt.Color(86, 169, 222));
        laporanHasilSeleksi.setText("      Laporan Hasil Seleksi");
        laporanHasilSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanHasilSeleksi.setOpaque(true);
        laporanHasilSeleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporanDataPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(alternatif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(laporanDataPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(91, 174, 228));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                                                     Sistem Pendukung Keputusan Pemesanan Makanan dan Minuman Online Pada Coffe Shop Echo Space");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(91, 174, 228));
        content.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternatifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alternatifMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show(ContentPanel, "alternatif");
    }//GEN-LAST:event_alternatifMouseClicked

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show(ContentPanel, "kriteria");
    }//GEN-LAST:event_kriteriaMouseClicked

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show(ContentPanel, "seleksi");
    }//GEN-LAST:event_seleksiMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) ContentPanel.getLayout();
        cl.show(ContentPanel, "laporan");
    }//GEN-LAST:event_laporanMouseClicked

    private void laporanDataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanDataPaketMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/laporan/LaporanPaketMakanan.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","src/image/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanDataPaketMouseClicked

    private void laporanDataPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanDataPaketMouseEntered
        // TODO add your handling code here:
        laporanDataPaket.setBackground(new Color(51,51,51));
        laporanDataPaket.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanDataPaketMouseEntered

    private void laporanDataPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanDataPaketMouseExited
        // TODO add your handling code here:
        laporanDataPaket.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanDataPaketMouseExited

    private void laporanPrioritasKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/laporan/LaporanPrioritasKriteria.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","src/image/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseClicked

    private void laporanPrioritasKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseExited
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseExited

    private void laporanPrioritasKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseEntered
        // TODO add your handling code here:
        laporanPrioritasKriteria.setBackground(new Color(51,51,51));
        laporanPrioritasKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseEntered

    private void laporanHasilSeleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseClicked
        // TODO add your handling code here:
        try{
            String namaFile = "src/laporan/LaporanHasilSeleksi.jasper";
            HashMap parameter = new HashMap();
            parameter.put("PATH_IMG","src/image/");
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_laporanHasilSeleksiMouseClicked

    private void laporanHasilSeleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseExited
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(80,80,80));
    }//GEN-LAST:event_laporanHasilSeleksiMouseExited

    private void laporanHasilSeleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseEntered
        // TODO add your handling code here:
        laporanHasilSeleksi.setBackground(new Color(51,51,51));
        laporanHasilSeleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanHasilSeleksiMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel ContentPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternatif;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton kriteria;
    private javax.swing.JButton laporan;
    private javax.swing.JLabel laporanDataPaket;
    private javax.swing.JLabel laporanHasilSeleksi;
    private javax.swing.JLabel laporanPrioritasKriteria;
    private javax.swing.JButton seleksi;
    // End of variables declaration//GEN-END:variables
}
